# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

func_dc <- function(z) {
    .Call('_BSCOV_func_dc', PACKAGE = 'BSCOV', z)
}

func_dc_by <- function(z, dmby, dtby) {
    .Call('_BSCOV_func_dc_by', PACKAGE = 'BSCOV', z, dmby, dtby)
}

func_coef <- function(z, scale) {
    .Call('_BSCOV_func_coef', PACKAGE = 'BSCOV', z, scale)
}

func_input <- function(coef, sgn) {
    .Call('_BSCOV_func_input', PACKAGE = 'BSCOV', coef, sgn)
}

func_input_on <- function(coef) {
    .Call('_BSCOV_func_input_on', PACKAGE = 'BSCOV', coef)
}

